// ============================================================================
// Judo Technique Database
// ----------------------------------------------------------------------------
// 60+ technique entries used for athlete profiling, weekly technical
// periodization, and judo session generation. Data fields are coach-curated
// approximations meant to drive theme/emphasis logic, NOT a clinical taxonomy.
// ============================================================================

export interface Technique {
  id: string
  name: string
  japaneseName: string
  type: 'te-waza' | 'koshi-waza' | 'ashi-waza' | 'sutemi-waza' | 'ne-waza'
  direction: 'forward' | 'backward' | 'side' | 'circular'
  stanceCompat: ('RR' | 'RL' | 'LL')[]
  attackDistance: 'close' | 'medium' | 'long'
  gripRequirements: string[]
  complexityLevel: 1 | 2 | 3
  energyDemand: 1 | 2 | 3
  speedRequirement: 1 | 2 | 3
  mobilityRequirement: 1 | 2 | 3
  combinationsWith: string[]
  countersWith: string[]
  transitionsTo: string[]
  edgeFightingCompatible: boolean
  goldenScoreCompatible: boolean
  tags: string[]
}

export const TECHNIQUES: Technique[] = [
  // ---------------------------------------------------------------------
  // TE-WAZA (hand techniques)
  // ---------------------------------------------------------------------
  {
    id: 'seoi-nage',
    name: 'Seoi Nage',
    japaneseName: '背負投',
    type: 'te-waza',
    direction: 'forward',
    stanceCompat: ['RR', 'LL'],
    attackDistance: 'close',
    gripRequirements: ['sleeve', 'lapel'],
    complexityLevel: 2,
    energyDemand: 2,
    speedRequirement: 3,
    mobilityRequirement: 3,
    combinationsWith: ['ko-uchi-gari', 'o-uchi-gari', 'sasae-tsuri-komi-ashi'],
    countersWith: ['ura-nage', 'tani-otoshi'],
    transitionsTo: ['juji-gatame', 'kesa-gatame', 'yoko-shiho-gatame'],
    edgeFightingCompatible: true,
    goldenScoreCompatible: true,
    tags: ['signature', 'explosive', 'forward'],
  },
  {
    id: 'morote-seoi-nage',
    name: 'Morote Seoi Nage',
    japaneseName: '両手背負投',
    type: 'te-waza',
    direction: 'forward',
    stanceCompat: ['RR', 'LL'],
    attackDistance: 'close',
    gripRequirements: ['sleeve', 'lapel'],
    complexityLevel: 2,
    energyDemand: 2,
    speedRequirement: 3,
    mobilityRequirement: 3,
    combinationsWith: ['ko-uchi-gari', 'sasae-tsuri-komi-ashi', 'o-uchi-gari'],
    countersWith: ['ura-nage'],
    transitionsTo: ['juji-gatame', 'kesa-gatame'],
    edgeFightingCompatible: true,
    goldenScoreCompatible: true,
    tags: ['signature', 'explosive', 'two-handed'],
  },
  {
    id: 'ippon-seoi-nage',
    name: 'Ippon Seoi Nage',
    japaneseName: '一本背負投',
    type: 'te-waza',
    direction: 'forward',
    stanceCompat: ['RR', 'RL', 'LL'],
    attackDistance: 'close',
    gripRequirements: ['sleeve'],
    complexityLevel: 2,
    energyDemand: 2,
    speedRequirement: 3,
    mobilityRequirement: 3,
    combinationsWith: ['ko-uchi-gari', 'sasae-tsuri-komi-ashi'],
    countersWith: ['ura-nage', 'tani-otoshi'],
    transitionsTo: ['juji-gatame', 'yoko-shiho-gatame'],
    edgeFightingCompatible: true,
    goldenScoreCompatible: true,
    tags: ['single-arm', 'forward', 'opposite-grip-friendly'],
  },
  {
    id: 'seoi-otoshi',
    name: 'Seoi Otoshi',
    japaneseName: '背負落',
    type: 'te-waza',
    direction: 'forward',
    stanceCompat: ['RR', 'LL'],
    attackDistance: 'close',
    gripRequirements: ['sleeve', 'lapel'],
    complexityLevel: 3,
    energyDemand: 2,
    speedRequirement: 3,
    mobilityRequirement: 3,
    combinationsWith: ['ko-uchi-gari', 'o-uchi-gari'],
    countersWith: ['ura-nage'],
    transitionsTo: ['juji-gatame', 'kesa-gatame'],
    edgeFightingCompatible: true,
    goldenScoreCompatible: true,
    tags: ['drop', 'low-entry'],
  },
  {
    id: 'tai-otoshi',
    name: 'Tai Otoshi',
    japaneseName: '体落',
    type: 'te-waza',
    direction: 'forward',
    stanceCompat: ['RR', 'LL'],
    attackDistance: 'medium',
    gripRequirements: ['sleeve', 'lapel'],
    complexityLevel: 2,
    energyDemand: 2,
    speedRequirement: 3,
    mobilityRequirement: 2,
    combinationsWith: ['ko-uchi-gari', 'o-uchi-gari'],
    countersWith: ['ko-uchi-gari', 'tani-otoshi'],
    transitionsTo: ['juji-gatame', 'yoko-shiho-gatame'],
    edgeFightingCompatible: true,
    goldenScoreCompatible: true,
    tags: ['blocking', 'wide-stance'],
  },
  {
    id: 'kata-guruma',
    name: 'Kata Guruma',
    japaneseName: '肩車',
    type: 'te-waza',
    direction: 'forward',
    stanceCompat: ['RR', 'RL', 'LL'],
    attackDistance: 'close',
    gripRequirements: ['sleeve', 'lapel', 'belt'],
    complexityLevel: 3,
    energyDemand: 3,
    speedRequirement: 2,
    mobilityRequirement: 3,
    combinationsWith: ['ko-uchi-gari', 'o-uchi-gari'],
    countersWith: ['tani-otoshi'],
    transitionsTo: ['kesa-gatame', 'tate-shiho-gatame'],
    edgeFightingCompatible: false,
    goldenScoreCompatible: true,
    tags: ['shoulder-carry', 'physical'],
  },
  {
    id: 'sukui-nage',
    name: 'Sukui Nage',
    japaneseName: '掬投',
    type: 'te-waza',
    direction: 'backward',
    stanceCompat: ['RR', 'RL', 'LL'],
    attackDistance: 'close',
    gripRequirements: ['belt', 'underhook'],
    complexityLevel: 3,
    energyDemand: 3,
    speedRequirement: 2,
    mobilityRequirement: 2,
    combinationsWith: [],
    countersWith: ['o-soto-gari'],
    transitionsTo: ['kesa-gatame', 'kami-shiho-gatame'],
    edgeFightingCompatible: false,
    goldenScoreCompatible: false,
    tags: ['scoop', 'broken-grip'],
  },

  // ---------------------------------------------------------------------
  // KOSHI-WAZA (hip techniques)
  // ---------------------------------------------------------------------
  {
    id: 'ogoshi',
    name: 'O Goshi',
    japaneseName: '大腰',
    type: 'koshi-waza',
    direction: 'forward',
    stanceCompat: ['RR', 'LL'],
    attackDistance: 'close',
    gripRequirements: ['lapel', 'belt-wrap'],
    complexityLevel: 1,
    energyDemand: 2,
    speedRequirement: 2,
    mobilityRequirement: 2,
    combinationsWith: ['ko-uchi-gari', 'o-uchi-gari'],
    countersWith: ['ura-nage', 'tani-otoshi'],
    transitionsTo: ['kesa-gatame'],
    edgeFightingCompatible: true,
    goldenScoreCompatible: false,
    tags: ['foundation', 'beginner-friendly'],
  },
  {
    id: 'koshi-guruma',
    name: 'Koshi Guruma',
    japaneseName: '腰車',
    type: 'koshi-waza',
    direction: 'forward',
    stanceCompat: ['RR', 'LL'],
    attackDistance: 'close',
    gripRequirements: ['neck', 'sleeve'],
    complexityLevel: 1,
    energyDemand: 2,
    speedRequirement: 2,
    mobilityRequirement: 2,
    combinationsWith: ['ko-uchi-gari'],
    countersWith: ['ura-nage', 'tani-otoshi'],
    transitionsTo: ['kesa-gatame'],
    edgeFightingCompatible: true,
    goldenScoreCompatible: false,
    tags: ['head-control', 'foundation'],
  },
  {
    id: 'uki-goshi',
    name: 'Uki Goshi',
    japaneseName: '浮腰',
    type: 'koshi-waza',
    direction: 'forward',
    stanceCompat: ['RR', 'LL'],
    attackDistance: 'close',
    gripRequirements: ['lapel', 'belt'],
    complexityLevel: 1,
    energyDemand: 2,
    speedRequirement: 2,
    mobilityRequirement: 2,
    combinationsWith: ['ko-uchi-gari'],
    countersWith: ['tani-otoshi'],
    transitionsTo: ['kesa-gatame'],
    edgeFightingCompatible: true,
    goldenScoreCompatible: false,
    tags: ['classical', 'foundation'],
  },
  {
    id: 'harai-goshi',
    name: 'Harai Goshi',
    japaneseName: '払腰',
    type: 'koshi-waza',
    direction: 'forward',
    stanceCompat: ['RR', 'LL'],
    attackDistance: 'medium',
    gripRequirements: ['sleeve', 'lapel'],
    complexityLevel: 2,
    energyDemand: 3,
    speedRequirement: 2,
    mobilityRequirement: 3,
    combinationsWith: ['ko-uchi-gari', 'o-uchi-gari', 'sasae-tsuri-komi-ashi'],
    countersWith: ['uchi-mata-sukashi', 'ura-nage'],
    transitionsTo: ['juji-gatame', 'yoko-shiho-gatame'],
    edgeFightingCompatible: true,
    goldenScoreCompatible: true,
    tags: ['sweeping-hip', 'signature'],
  },
  {
    id: 'tsuri-komi-goshi',
    name: 'Tsuri Komi Goshi',
    japaneseName: '釣込腰',
    type: 'koshi-waza',
    direction: 'forward',
    stanceCompat: ['RR', 'LL'],
    attackDistance: 'close',
    gripRequirements: ['sleeve', 'lapel'],
    complexityLevel: 2,
    energyDemand: 2,
    speedRequirement: 2,
    mobilityRequirement: 2,
    combinationsWith: ['ko-uchi-gari', 'o-uchi-gari'],
    countersWith: ['tani-otoshi'],
    transitionsTo: ['kesa-gatame', 'juji-gatame'],
    edgeFightingCompatible: true,
    goldenScoreCompatible: true,
    tags: ['lifting-pulling', 'foundation'],
  },
  {
    id: 'hane-goshi',
    name: 'Hane Goshi',
    japaneseName: '跳腰',
    type: 'koshi-waza',
    direction: 'forward',
    stanceCompat: ['RR', 'LL'],
    attackDistance: 'medium',
    gripRequirements: ['sleeve', 'lapel'],
    complexityLevel: 3,
    energyDemand: 3,
    speedRequirement: 2,
    mobilityRequirement: 3,
    combinationsWith: ['ko-uchi-gari', 'o-uchi-gari'],
    countersWith: ['uchi-mata-sukashi', 'ura-nage'],
    transitionsTo: ['juji-gatame'],
    edgeFightingCompatible: true,
    goldenScoreCompatible: true,
    tags: ['springing-hip', 'advanced'],
  },
  {
    id: 'sode-tsuri-komi-goshi',
    name: 'Sode Tsuri Komi Goshi',
    japaneseName: '袖釣込腰',
    type: 'koshi-waza',
    direction: 'forward',
    stanceCompat: ['RR', 'RL', 'LL'],
    attackDistance: 'close',
    gripRequirements: ['double-sleeve'],
    complexityLevel: 3,
    energyDemand: 2,
    speedRequirement: 3,
    mobilityRequirement: 3,
    combinationsWith: ['ko-uchi-gari', 'sasae-tsuri-komi-ashi'],
    countersWith: ['ura-nage'],
    transitionsTo: ['juji-gatame'],
    edgeFightingCompatible: true,
    goldenScoreCompatible: true,
    tags: ['sleeve-lift', 'cross-stance'],
  },
  {
    id: 'tsuri-goshi',
    name: 'Tsuri Goshi',
    japaneseName: '釣腰',
    type: 'koshi-waza',
    direction: 'forward',
    stanceCompat: ['RR', 'LL'],
    attackDistance: 'close',
    gripRequirements: ['lapel', 'belt'],
    complexityLevel: 2,
    energyDemand: 2,
    speedRequirement: 2,
    mobilityRequirement: 2,
    combinationsWith: ['ko-uchi-gari'],
    countersWith: ['ura-nage'],
    transitionsTo: ['kesa-gatame'],
    edgeFightingCompatible: true,
    goldenScoreCompatible: false,
    tags: ['belt-grip'],
  },

  // ---------------------------------------------------------------------
  // ASHI-WAZA (foot/leg techniques)
  // ---------------------------------------------------------------------
  {
    id: 'ko-uchi-gari',
    name: 'Ko Uchi Gari',
    japaneseName: '小内刈',
    type: 'ashi-waza',
    direction: 'backward',
    stanceCompat: ['RR', 'LL'],
    attackDistance: 'close',
    gripRequirements: ['sleeve', 'lapel'],
    complexityLevel: 1,
    energyDemand: 1,
    speedRequirement: 3,
    mobilityRequirement: 2,
    combinationsWith: ['morote-seoi-nage', 'tai-otoshi', 'uchi-mata', 'harai-goshi'],
    countersWith: ['tai-otoshi'],
    transitionsTo: ['juji-gatame', 'kesa-gatame'],
    edgeFightingCompatible: true,
    goldenScoreCompatible: true,
    tags: ['setup', 'foundation', 'combination-king'],
  },
  {
    id: 'o-uchi-gari',
    name: 'O Uchi Gari',
    japaneseName: '大内刈',
    type: 'ashi-waza',
    direction: 'backward',
    stanceCompat: ['RR', 'RL'],
    attackDistance: 'medium',
    gripRequirements: ['sleeve', 'lapel'],
    complexityLevel: 1,
    energyDemand: 2,
    speedRequirement: 2,
    mobilityRequirement: 2,
    combinationsWith: ['uchi-mata', 'harai-goshi', 'morote-seoi-nage', 'tai-otoshi'],
    countersWith: ['ura-nage', 'sukui-nage'],
    transitionsTo: ['kesa-gatame', 'juji-gatame'],
    edgeFightingCompatible: true,
    goldenScoreCompatible: true,
    tags: ['setup', 'foundation', 'opposite-stance-friendly'],
  },
  {
    id: 'ko-soto-gari',
    name: 'Ko Soto Gari',
    japaneseName: '小外刈',
    type: 'ashi-waza',
    direction: 'backward',
    stanceCompat: ['RR', 'RL', 'LL'],
    attackDistance: 'close',
    gripRequirements: ['sleeve', 'lapel'],
    complexityLevel: 2,
    energyDemand: 1,
    speedRequirement: 3,
    mobilityRequirement: 2,
    combinationsWith: ['o-uchi-gari', 'tai-otoshi'],
    countersWith: ['ko-soto-gari'],
    transitionsTo: ['kesa-gatame', 'yoko-shiho-gatame'],
    edgeFightingCompatible: true,
    goldenScoreCompatible: true,
    tags: ['outside-trip', 'counter-friendly'],
  },
  {
    id: 'o-soto-gari',
    name: 'O Soto Gari',
    japaneseName: '大外刈',
    type: 'ashi-waza',
    direction: 'backward',
    stanceCompat: ['RR', 'LL'],
    attackDistance: 'close',
    gripRequirements: ['sleeve', 'lapel'],
    complexityLevel: 1,
    energyDemand: 2,
    speedRequirement: 2,
    mobilityRequirement: 2,
    combinationsWith: ['o-uchi-gari', 'ko-soto-gari'],
    countersWith: ['o-soto-gari', 'ura-nage'],
    transitionsTo: ['kesa-gatame', 'kami-shiho-gatame'],
    edgeFightingCompatible: true,
    goldenScoreCompatible: true,
    tags: ['major-outer', 'foundation'],
  },
  {
    id: 'sasae-tsuri-komi-ashi',
    name: 'Sasae Tsuri Komi Ashi',
    japaneseName: '支釣込足',
    type: 'ashi-waza',
    direction: 'forward',
    stanceCompat: ['RR', 'LL'],
    attackDistance: 'medium',
    gripRequirements: ['sleeve', 'lapel'],
    complexityLevel: 2,
    energyDemand: 1,
    speedRequirement: 3,
    mobilityRequirement: 3,
    combinationsWith: ['morote-seoi-nage', 'uchi-mata', 'tai-otoshi', 'sode-tsuri-komi-goshi'],
    countersWith: ['tai-otoshi'],
    transitionsTo: ['juji-gatame', 'yoko-shiho-gatame'],
    edgeFightingCompatible: true,
    goldenScoreCompatible: true,
    tags: ['prop-throw', 'timing'],
  },
  {
    id: 'harai-tsuri-komi-ashi',
    name: 'Harai Tsuri Komi Ashi',
    japaneseName: '払釣込足',
    type: 'ashi-waza',
    direction: 'forward',
    stanceCompat: ['RR', 'LL'],
    attackDistance: 'medium',
    gripRequirements: ['sleeve', 'lapel'],
    complexityLevel: 2,
    energyDemand: 1,
    speedRequirement: 3,
    mobilityRequirement: 3,
    combinationsWith: ['morote-seoi-nage', 'tai-otoshi'],
    countersWith: ['tai-otoshi'],
    transitionsTo: ['juji-gatame'],
    edgeFightingCompatible: true,
    goldenScoreCompatible: true,
    tags: ['sweep-prop', 'timing'],
  },
  {
    id: 'deashi-barai',
    name: 'Deashi Barai',
    japaneseName: '出足払',
    type: 'ashi-waza',
    direction: 'side',
    stanceCompat: ['RR', 'RL', 'LL'],
    attackDistance: 'medium',
    gripRequirements: ['sleeve'],
    complexityLevel: 2,
    energyDemand: 1,
    speedRequirement: 3,
    mobilityRequirement: 3,
    combinationsWith: ['tai-otoshi', 'morote-seoi-nage'],
    countersWith: ['deashi-barai'],
    transitionsTo: ['yoko-shiho-gatame'],
    edgeFightingCompatible: true,
    goldenScoreCompatible: true,
    tags: ['timing', 'movement-throw'],
  },
  {
    id: 'okuri-ashi-barai',
    name: 'Okuri Ashi Barai',
    japaneseName: '送足払',
    type: 'ashi-waza',
    direction: 'side',
    stanceCompat: ['RR', 'RL', 'LL'],
    attackDistance: 'medium',
    gripRequirements: ['sleeve', 'lapel'],
    complexityLevel: 3,
    energyDemand: 1,
    speedRequirement: 3,
    mobilityRequirement: 3,
    combinationsWith: ['tai-otoshi'],
    countersWith: [],
    transitionsTo: ['yoko-shiho-gatame'],
    edgeFightingCompatible: true,
    goldenScoreCompatible: true,
    tags: ['advanced-timing', 'lateral'],
  },
  {
    id: 'uchi-mata',
    name: 'Uchi Mata',
    japaneseName: '内股',
    type: 'ashi-waza',
    direction: 'forward',
    stanceCompat: ['RR', 'RL', 'LL'],
    attackDistance: 'medium',
    gripRequirements: ['sleeve', 'lapel'],
    complexityLevel: 2,
    energyDemand: 3,
    speedRequirement: 3,
    mobilityRequirement: 3,
    combinationsWith: ['ko-uchi-gari', 'o-uchi-gari', 'sasae-tsuri-komi-ashi'],
    countersWith: ['uchi-mata-sukashi', 'tani-otoshi', 'ura-nage'],
    transitionsTo: ['juji-gatame', 'yoko-shiho-gatame'],
    edgeFightingCompatible: true,
    goldenScoreCompatible: true,
    tags: ['signature', 'world-class', 'explosive'],
  },
  {
    id: 'ko-uchi-gake',
    name: 'Ko Uchi Gake',
    japaneseName: '小内掛',
    type: 'ashi-waza',
    direction: 'backward',
    stanceCompat: ['RR', 'LL'],
    attackDistance: 'close',
    gripRequirements: ['sleeve', 'lapel'],
    complexityLevel: 2,
    energyDemand: 2,
    speedRequirement: 2,
    mobilityRequirement: 2,
    combinationsWith: ['morote-seoi-nage', 'tai-otoshi'],
    countersWith: ['tai-otoshi'],
    transitionsTo: ['kesa-gatame', 'yoko-shiho-gatame'],
    edgeFightingCompatible: true,
    goldenScoreCompatible: true,
    tags: ['hook', 'breakdown'],
  },
  {
    id: 'o-soto-gake',
    name: 'O Soto Gake',
    japaneseName: '大外掛',
    type: 'ashi-waza',
    direction: 'backward',
    stanceCompat: ['RR', 'LL'],
    attackDistance: 'close',
    gripRequirements: ['sleeve', 'lapel'],
    complexityLevel: 2,
    energyDemand: 2,
    speedRequirement: 2,
    mobilityRequirement: 2,
    combinationsWith: ['o-uchi-gari'],
    countersWith: ['o-soto-gari'],
    transitionsTo: ['kami-shiho-gatame', 'kesa-gatame'],
    edgeFightingCompatible: true,
    goldenScoreCompatible: true,
    tags: ['hook', 'pressure'],
  },
  {
    id: 'nidan-ko-soto',
    name: 'Nidan Ko Soto Gari',
    japaneseName: '二段小外刈',
    type: 'ashi-waza',
    direction: 'backward',
    stanceCompat: ['RR', 'LL'],
    attackDistance: 'medium',
    gripRequirements: ['sleeve', 'lapel'],
    complexityLevel: 3,
    energyDemand: 2,
    speedRequirement: 3,
    mobilityRequirement: 3,
    combinationsWith: ['o-uchi-gari'],
    countersWith: [],
    transitionsTo: ['yoko-shiho-gatame'],
    edgeFightingCompatible: true,
    goldenScoreCompatible: true,
    tags: ['running', 'two-step'],
  },

  // ---------------------------------------------------------------------
  // SUTEMI-WAZA (sacrifice techniques)
  // ---------------------------------------------------------------------
  {
    id: 'tomoe-nage',
    name: 'Tomoe Nage',
    japaneseName: '巴投',
    type: 'sutemi-waza',
    direction: 'backward',
    stanceCompat: ['RR', 'LL'],
    attackDistance: 'close',
    gripRequirements: ['sleeve', 'lapel'],
    complexityLevel: 2,
    energyDemand: 2,
    speedRequirement: 2,
    mobilityRequirement: 3,
    combinationsWith: ['ko-uchi-gari'],
    countersWith: ['ura-nage'],
    transitionsTo: ['juji-gatame', 'sankaku-jime'],
    edgeFightingCompatible: false,
    goldenScoreCompatible: false,
    tags: ['sacrifice', 'foot-in-belly'],
  },
  {
    id: 'ura-nage',
    name: 'Ura Nage',
    japaneseName: '裏投',
    type: 'sutemi-waza',
    direction: 'backward',
    stanceCompat: ['RR', 'RL', 'LL'],
    attackDistance: 'close',
    gripRequirements: ['underhook', 'belt'],
    complexityLevel: 3,
    energyDemand: 3,
    speedRequirement: 2,
    mobilityRequirement: 2,
    combinationsWith: [],
    countersWith: [],
    transitionsTo: ['kami-shiho-gatame', 'yoko-shiho-gatame'],
    edgeFightingCompatible: false,
    goldenScoreCompatible: true,
    tags: ['counter', 'physical', 'rear-sacrifice'],
  },
  {
    id: 'sumi-gaeshi',
    name: 'Sumi Gaeshi',
    japaneseName: '隅返',
    type: 'sutemi-waza',
    direction: 'backward',
    stanceCompat: ['RR', 'RL', 'LL'],
    attackDistance: 'close',
    gripRequirements: ['underhook', 'lapel'],
    complexityLevel: 3,
    energyDemand: 2,
    speedRequirement: 2,
    mobilityRequirement: 3,
    combinationsWith: [],
    countersWith: [],
    transitionsTo: ['juji-gatame', 'sankaku-jime'],
    edgeFightingCompatible: false,
    goldenScoreCompatible: false,
    tags: ['sacrifice', 'corner-throw'],
  },
  {
    id: 'yoko-tomoe-nage',
    name: 'Yoko Tomoe Nage',
    japaneseName: '横巴投',
    type: 'sutemi-waza',
    direction: 'side',
    stanceCompat: ['RR', 'RL', 'LL'],
    attackDistance: 'close',
    gripRequirements: ['sleeve', 'lapel'],
    complexityLevel: 3,
    energyDemand: 2,
    speedRequirement: 2,
    mobilityRequirement: 3,
    combinationsWith: [],
    countersWith: [],
    transitionsTo: ['juji-gatame', 'sankaku-jime'],
    edgeFightingCompatible: false,
    goldenScoreCompatible: false,
    tags: ['sacrifice', 'lateral'],
  },
  {
    id: 'tani-otoshi',
    name: 'Tani Otoshi',
    japaneseName: '谷落',
    type: 'sutemi-waza',
    direction: 'backward',
    stanceCompat: ['RR', 'RL', 'LL'],
    attackDistance: 'close',
    gripRequirements: ['sleeve', 'lapel'],
    complexityLevel: 2,
    energyDemand: 2,
    speedRequirement: 2,
    mobilityRequirement: 2,
    combinationsWith: [],
    countersWith: [],
    transitionsTo: ['kesa-gatame', 'yoko-shiho-gatame'],
    edgeFightingCompatible: true,
    goldenScoreCompatible: true,
    tags: ['counter', 'valley-drop'],
  },
  {
    id: 'uchi-mata-sukashi',
    name: 'Uchi Mata Sukashi',
    japaneseName: '内股透',
    type: 'sutemi-waza',
    direction: 'side',
    stanceCompat: ['RR', 'RL', 'LL'],
    attackDistance: 'medium',
    gripRequirements: ['sleeve', 'lapel'],
    complexityLevel: 3,
    energyDemand: 1,
    speedRequirement: 3,
    mobilityRequirement: 3,
    combinationsWith: [],
    countersWith: [],
    transitionsTo: ['yoko-shiho-gatame', 'juji-gatame'],
    edgeFightingCompatible: true,
    goldenScoreCompatible: true,
    tags: ['counter', 'evasion'],
  },
  {
    id: 'yoko-wakare',
    name: 'Yoko Wakare',
    japaneseName: '横分',
    type: 'sutemi-waza',
    direction: 'side',
    stanceCompat: ['RR', 'RL', 'LL'],
    attackDistance: 'close',
    gripRequirements: ['sleeve', 'lapel'],
    complexityLevel: 3,
    energyDemand: 2,
    speedRequirement: 2,
    mobilityRequirement: 3,
    combinationsWith: [],
    countersWith: [],
    transitionsTo: ['yoko-shiho-gatame', 'juji-gatame'],
    edgeFightingCompatible: false,
    goldenScoreCompatible: false,
    tags: ['sacrifice', 'lateral'],
  },

  // ---------------------------------------------------------------------
  // NE-WAZA (ground techniques)
  // ---------------------------------------------------------------------
  {
    id: 'juji-gatame',
    name: 'Juji Gatame',
    japaneseName: '十字固',
    type: 'ne-waza',
    direction: 'circular',
    stanceCompat: ['RR', 'RL', 'LL'],
    attackDistance: 'close',
    gripRequirements: ['wrist', 'arm'],
    complexityLevel: 2,
    energyDemand: 2,
    speedRequirement: 2,
    mobilityRequirement: 3,
    combinationsWith: ['sankaku-jime'],
    countersWith: [],
    transitionsTo: ['sankaku-jime'],
    edgeFightingCompatible: true,
    goldenScoreCompatible: true,
    tags: ['armbar', 'submission', 'finisher'],
  },
  {
    id: 'sankaku-jime',
    name: 'Sankaku Jime',
    japaneseName: '三角絞',
    type: 'ne-waza',
    direction: 'circular',
    stanceCompat: ['RR', 'RL', 'LL'],
    attackDistance: 'close',
    gripRequirements: ['leg-control'],
    complexityLevel: 3,
    energyDemand: 2,
    speedRequirement: 2,
    mobilityRequirement: 3,
    combinationsWith: ['juji-gatame'],
    countersWith: [],
    transitionsTo: ['juji-gatame', 'tate-shiho-gatame'],
    edgeFightingCompatible: true,
    goldenScoreCompatible: true,
    tags: ['triangle', 'choke', 'submission'],
  },
  {
    id: 'hadaka-jime',
    name: 'Hadaka Jime',
    japaneseName: '裸絞',
    type: 'ne-waza',
    direction: 'circular',
    stanceCompat: ['RR', 'RL', 'LL'],
    attackDistance: 'close',
    gripRequirements: ['rear-control'],
    complexityLevel: 2,
    energyDemand: 2,
    speedRequirement: 2,
    mobilityRequirement: 2,
    combinationsWith: [],
    countersWith: [],
    transitionsTo: ['tate-shiho-gatame'],
    edgeFightingCompatible: true,
    goldenScoreCompatible: true,
    tags: ['rear-naked', 'choke'],
  },
  {
    id: 'okuri-eri-jime',
    name: 'Okuri Eri Jime',
    japaneseName: '送襟絞',
    type: 'ne-waza',
    direction: 'circular',
    stanceCompat: ['RR', 'RL', 'LL'],
    attackDistance: 'close',
    gripRequirements: ['collar'],
    complexityLevel: 3,
    energyDemand: 2,
    speedRequirement: 2,
    mobilityRequirement: 2,
    combinationsWith: ['hadaka-jime'],
    countersWith: [],
    transitionsTo: ['tate-shiho-gatame'],
    edgeFightingCompatible: true,
    goldenScoreCompatible: true,
    tags: ['gi-choke', 'collar'],
  },
  {
    id: 'kesa-gatame',
    name: 'Kesa Gatame',
    japaneseName: '袈裟固',
    type: 'ne-waza',
    direction: 'side',
    stanceCompat: ['RR', 'RL', 'LL'],
    attackDistance: 'close',
    gripRequirements: ['sleeve', 'neck'],
    complexityLevel: 1,
    energyDemand: 2,
    speedRequirement: 1,
    mobilityRequirement: 1,
    combinationsWith: ['ude-garami'],
    countersWith: [],
    transitionsTo: ['ude-garami', 'kami-shiho-gatame'],
    edgeFightingCompatible: false,
    goldenScoreCompatible: true,
    tags: ['scarf-hold', 'foundation', 'pin'],
  },
  {
    id: 'yoko-shiho-gatame',
    name: 'Yoko Shiho Gatame',
    japaneseName: '横四方固',
    type: 'ne-waza',
    direction: 'side',
    stanceCompat: ['RR', 'RL', 'LL'],
    attackDistance: 'close',
    gripRequirements: ['lapel', 'belt'],
    complexityLevel: 1,
    energyDemand: 1,
    speedRequirement: 1,
    mobilityRequirement: 1,
    combinationsWith: ['ude-garami'],
    countersWith: [],
    transitionsTo: ['kami-shiho-gatame', 'tate-shiho-gatame'],
    edgeFightingCompatible: false,
    goldenScoreCompatible: true,
    tags: ['side-control', 'pin', 'foundation'],
  },
  {
    id: 'tate-shiho-gatame',
    name: 'Tate Shiho Gatame',
    japaneseName: '縦四方固',
    type: 'ne-waza',
    direction: 'circular',
    stanceCompat: ['RR', 'RL', 'LL'],
    attackDistance: 'close',
    gripRequirements: ['lapel'],
    complexityLevel: 2,
    energyDemand: 2,
    speedRequirement: 1,
    mobilityRequirement: 2,
    combinationsWith: ['hadaka-jime', 'juji-gatame'],
    countersWith: [],
    transitionsTo: ['hadaka-jime', 'juji-gatame'],
    edgeFightingCompatible: false,
    goldenScoreCompatible: true,
    tags: ['mount', 'pin'],
  },
  {
    id: 'kami-shiho-gatame',
    name: 'Kami Shiho Gatame',
    japaneseName: '上四方固',
    type: 'ne-waza',
    direction: 'forward',
    stanceCompat: ['RR', 'RL', 'LL'],
    attackDistance: 'close',
    gripRequirements: ['belt'],
    complexityLevel: 1,
    energyDemand: 1,
    speedRequirement: 1,
    mobilityRequirement: 1,
    combinationsWith: [],
    countersWith: [],
    transitionsTo: ['kesa-gatame', 'yoko-shiho-gatame'],
    edgeFightingCompatible: false,
    goldenScoreCompatible: true,
    tags: ['north-south', 'pin', 'foundation'],
  },
  {
    id: 'ude-garami',
    name: 'Ude Garami',
    japaneseName: '腕緘',
    type: 'ne-waza',
    direction: 'side',
    stanceCompat: ['RR', 'RL', 'LL'],
    attackDistance: 'close',
    gripRequirements: ['wrist'],
    complexityLevel: 2,
    energyDemand: 2,
    speedRequirement: 1,
    mobilityRequirement: 2,
    combinationsWith: ['kesa-gatame'],
    countersWith: [],
    transitionsTo: ['juji-gatame'],
    edgeFightingCompatible: false,
    goldenScoreCompatible: true,
    tags: ['kimura', 'shoulder-lock', 'submission'],
  },
  {
    id: 'waki-gatame',
    name: 'Waki Gatame',
    japaneseName: '腋固',
    type: 'ne-waza',
    direction: 'side',
    stanceCompat: ['RR', 'RL', 'LL'],
    attackDistance: 'close',
    gripRequirements: ['wrist', 'arm'],
    complexityLevel: 3,
    energyDemand: 2,
    speedRequirement: 2,
    mobilityRequirement: 2,
    combinationsWith: ['juji-gatame'],
    countersWith: [],
    transitionsTo: ['juji-gatame'],
    edgeFightingCompatible: false,
    goldenScoreCompatible: true,
    tags: ['armpit-lock', 'submission'],
  },
]

export const TECHNIQUE_MAP: Map<string, Technique> = new Map(
  TECHNIQUES.map(t => [t.id, t]),
)

// ---------------------------------------------------------------------------
// Helpers
// ---------------------------------------------------------------------------

export function getTechnique(id: string): Technique | undefined {
  return TECHNIQUE_MAP.get(id)
}

export function techniqueLabel(id: string): string {
  return TECHNIQUE_MAP.get(id)?.name ?? id
}

export function techniquesByType(type: Technique['type']): Technique[] {
  return TECHNIQUES.filter(t => t.type === type)
}
